# Generated by Django 3.2.19 on 2023-05-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateField(auto_now=True, verbose_name='fecha_venta')),
                ('sabor_helado', models.CharField(max_length=255, verbose_name='sabor_helado')),
                ('cantidad', models.IntegerField(verbose_name='cantidad')),
                ('gramos_unidad', models.IntegerField(verbose_name='gramos_unidad')),
            ],
        ),
    ]
