# Generated by Django 3.2.19 on 2023-05-18 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vista', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
